version: 1.0.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}-prerelease'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: >-
    nuget restore ./TriggersTools.SharpUtils.sln
#build:
#  project: TriggersTools.SharpUtils.sln      # path to Visual Studio solution or project
#  publish_nuget: true                        # package projects with .nuspec files and push to artifacts
configuration: Release
artifacts:
- path: 'src\*\bin\**\*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: QVGLofIy2zySjb1ZW8e730tg6PxVB+++YvaJh/Dc54LA6h6u+2Cf4davQ9PPGn7E
  artifact: /.*\.nupkg/
  
  on:
    branch: master
    appveyor_repo_tag: true
