version: '0.0.1.{build}'
environment:
  baseVersion: '0.0.3'
  
image: Visual Studio 2017
configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(packageVersion)'
  package_version: '$(packageVersion)'
  assembly_version: '$(buildVersion)'
  file_version: '$(buildVersion)'
  informational_version: '$(packageVersion)'

#branches:
#  only:
#    - master

before_build:
- nuget restore

artifacts:
- path: '**\*.nupkg'

for:
# Other
-
  skip_commits:
    message: /^@appveyor-(?:build|release)/
  init:
  - cmd: '@ECHO ==== TEST BUILD ===='
  - ps: $env:buildVersion = "$env:baseVersion.$env:appveyor_build_number"
  - ps: $env:packageVersion = "$env:baseVersion-build-$env:appveyor_build_number"
  - ps: Update-AppveyorBuild -Version $env:buildVersion

# Testing
-
  only_commits:
    message: /^@appveyor-test/
  init:
  - cmd: '@ECHO ==== DESCRIPTION TEST BUILD ===='
  - ps: $env:buildVersion = "$env:baseVersion.$env:appveyor_build_number"
  - ps: $env:packageVersion = "$env:baseVersion-build-$env:appveyor_build_number"
  - ps: Update-AppveyorBuild -Version $env:buildVersion

# Pre-release
-
  only_commits:
    message: /^@appveyor-build/
  init:
  - cmd: '@ECHO ==== PRE-RELEASE BUILD ===='
  - ps: $env:buildVersion = "$env:baseVersion.$env:appveyor_build_number"
  - ps: $env:packageVersion = "$env:baseVersion-build-$env:appveyor_build_number"
  - ps: Update-AppveyorBuild -Version $env:buildVersion
  deploy:
    provider: NuGet
    api_key:
      secure: QVGLofIy2zySjb1ZW8e730tg6PxVB+++YvaJh/Dc54LA6h6u+2Cf4davQ9PPGn7E
    artifact: /.*\.nupkg/

# Release
-
  only_commits:
    message: /^@appveyor-release/
  init:
  - cmd: '@ECHO ==== RELEASE BUILD ===='
  - ps: $env:buildVersion = "$env:baseVersion.$env:appveyor_build_number"
  - ps: $env:packageVersion = "$env:baseVersion"
  - ps: Update-AppveyorBuild -Version $env:buildVersion
  deploy:
    provider: NuGet
    api_key:
      secure: QVGLofIy2zySjb1ZW8e730tg6PxVB+++YvaJh/Dc54LA6h6u+2Cf4davQ9PPGn7E
    artifact: /.*\.nupkg/
