version: '1.0.0.{build}'
environment:
  baseVersion: 1.0.0

init:
- ps: $env:buildVersion = "$env:baseVersion.$env:appveyor_build_number"
- ps: $env:packageVersion = "$env:baseVersion-beta-$env:appveyor_build_number"
- ps: Update-AppveyorBuild -Version $env:buildVersion
  
image: Visual Studio 2017
configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(packageVersion)'
  package_version: '$(packageVersion)'
  assembly_version: '$(buildVersion)'
  file_version: '$(buildVersion)'
  informational_version: '$(packageVersion)'

before_build:
- nuget restore

artifacts:
- path: '**\*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: QVGLofIy2zySjb1ZW8e730tg6PxVB+++YvaJh/Dc54LA6h6u+2Cf4davQ9PPGn7E
  artifact: /.*\.nupkg/
  on:
    branch: master
