
image: Visual Studio 2017

version: '0.0.1.{build}'
environment:
  baseVersion: 0.0.2
#  buildVersion: '{packageVersion}.{build}'
#  nugetVersion: '{packageVersion}-beta-{build}'

init:
- ps: $env:buildVersion = "$env:baseVersion.$env:appveyor_build_number"
- ps: $env:packageVersion = "$env:baseVersion-beta-$env:appveyor_build_number"
- ps: Update-AppveyorBuild -Version $env:buildVersion


dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(packageVersion)'
  package_version: '$(packageVersion)'
  assembly_version: '$(buildVersion)'
  file_version: '$(buildVersion)'
  informational_version: '$(packageVersion)'

before_build:
- nuget restore
#build:
#  publish_nuget: true

configuration: Release
#platform: Any CPU

artifacts:
- path: '**\*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: QVGLofIy2zySjb1ZW8e730tg6PxVB+++YvaJh/Dc54LA6h6u+2Cf4davQ9PPGn7E
  artifact: /.*\.nupkg/
  on:
    branch: master
